CREATE TABLE PACIENTE (
  ID NUMBER NOT NULL PRIMARY KEY,
  CPF VARCHAR2(11) NOT NULL UNIQUE,
  EMAIL VARCHAR2(255) NOT NULL,
  NOME VARCHAR2(120) NOT NULL
);

CREATE TABLE MEDICO (
  ID NUMBER NOT NULL PRIMARY KEY,
  CRM VARCHAR2(30) NOT NULL UNIQUE,
  NOME VARCHAR2(120) NOT NULL
);

CREATE TABLE CONSULTA (
  ID NUMBER NOT NULL PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL,
  MEDICO_ID NUMBER NOT NULL,
  STATUS VARCHAR2(20) NOT NULL,
  DATA_HORA TIMESTAMP NOT NULL,
  CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
  CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(ID)
);

CREATE SEQUENCE PACIENTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONSULTA_SEQ START WITH 1 INCREMENT BY 1;