-- Cria as tabelas com IDs simples
CREATE TABLE PACIENTE (
  ID NUMBER NOT NULL PRIMARY KEY,
  CPF VARCHAR2(11) NOT NULL UNIQUE,
  EMAIL VARCHAR2(255) NOT NULL,
  NOME VARCHAR2(120) NOT NULL
);

CREATE TABLE MEDICO (
  ID NUMBER NOT NULL PRIMARY KEY,
  CRM VARCHAR2(30) NOT NULL UNIQUE,
  NOME VARCHAR2(120) NOT NULL
);

CREATE TABLE CONSULTA (
  ID NUMBER NOT NULL PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL,
  MEDICO_ID NUMBER NOT NULL,
  STATUS VARCHAR2(20) NOT NULL,
  DATA_HORA TIMESTAMP NOT NULL,
  CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
  CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(ID)
);

-- Cria as SEQUENCES para gerar os IDs
CREATE SEQUENCE PACIENTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONSULTA_SEQ START WITH 1 INCREMENT BY 1;

-- Cria os TRIGGERS para usar as SEQUENCES automaticamente antes de cada INSERT
CREATE OR REPLACE TRIGGER TRG_PACIENTE_ID
BEFORE INSERT ON PACIENTE
FOR EACH ROW
BEGIN
  :NEW.ID := PACIENTE_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MEDICO_ID
BEFORE INSERT ON MEDICO
FOR EACH ROW
BEGIN
  :NEW.ID := MEDICO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONSULTA_ID
BEFORE INSERT ON CONSULTA
FOR EACH ROW
BEGIN
  :NEW.ID := CONSULTA_SEQ.NEXTVAL;
END;
/